name = "Neutrals"
uuid = "789cc80b-6f9a-47a7-8588-bb01047265c3"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.3.5"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
Aqua = "0.8"
Requires = "1"
Test = "<0.0.1, 1"
TypeUtils = "1.13"
Unitful = "1"
julia = "1"

[extensions]
NeutralsUnitfulExt = "Unitful"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "Test", "Unitful"]

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
